services:
  bot:
    build:
      context: .
      dockerfile: Discord-Music/Dockerfile
    container_name: discord-music-bot
    restart: unless-stopped
    volumes:
      - ./Discord-Music/Config.json:/app/Config.json
      - ./Discord-Music/Languages:/app/Languages
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"